#   ___________                __         ___________
#  /   _____/__| _____ ______ |  |   ____ \__    ___/____     ____   ______
#  \_____  \|  |/     \\____ \|  | _/ __ \  |    |  \__  \   / ___\ /  ___/
#  /        \  |  | |  \  |_\ \  |__  ___/_ |    |   / __ \_/ /_/  \\___ \
# /_______  /__|__|_|  /   ___/____/\___  / |____|  (____  /\___  //____
#         \/         \/|__|             \/               \//_____/      \/

# The locale to use in the /locale folder
# Available Locales:
# en_US (Default)
# zh_CN
locale: en_US

# Should player's be required to have the tag permission
# in order to see it in commands and menus
# they will still need to have the permission to equip the tag either way
require-permission: false

# Automatically add tags to chat behind a player's name
# This setting should only be used if
# you don't have a chat plugin
use-chat: false

# Choose your data saving type:
# MYSQL/MARIADB - Database saving
# SQLITE - Local database saving in a .db file
data-type: SQLITE

# Either MySQL or MariaDB will work here.
mysql:
  host: 127.0.0.1
  port: '3306'
  database: SimpleTags
  username: ''
  password: ''

# Check for updates on join
# This uses the /tags version command permission
# permission: simpletags.command.version
check-for-updates: true